# Generated by Django 5.1.1 on 2025-09-01 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Mã ngân hàng')),
                ('name', models.CharField(max_length=120, verbose_name='Tên ngân hàng')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='SĐT')),
                ('image', models.URLField(blank=True, verbose_name='Ảnh (URL)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
            ],
            options={
                'verbose_name': 'Ngân hàng',
                'verbose_name_plural': 'Ngân hàng',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='map_bank_name_18bf6a_idx'), models.Index(fields=['latitude', 'longitude'], name='map_bank_latitud_8b2774_idx')],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.CharField(max_length=20, verbose_name='Mã chi nhánh')),
                ('name', models.CharField(max_length=120, verbose_name='Tên chi nhánh')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='SĐT')),
                ('image', models.URLField(blank=True, verbose_name='Ảnh (URL)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='map.bank', verbose_name='Ngân hàng')),
            ],
            options={
                'verbose_name': 'Chi nhánh',
                'verbose_name_plural': 'Chi nhánh',
                'ordering': ['bank__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Mã ATM')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('maintenance', 'Bảo trì'), ('offline', 'Ngừng/Offline')], default='active', max_length=20, verbose_name='Tình trạng')),
                ('image', models.URLField(blank=True, verbose_name='Ảnh (URL)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atms', to='map.branch', verbose_name='Chi nhánh')),
            ],
            options={
                'verbose_name': 'ATM',
                'verbose_name_plural': 'ATM',
                'ordering': ['branch__name', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['bank', 'name'], name='map_branch_bank_id_63c534_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['latitude', 'longitude'], name='map_branch_latitud_23ba81_idx'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('bank', 'code'), name='uq_branch_bank_code'),
        ),
        migrations.AddIndex(
            model_name='atm',
            index=models.Index(fields=['branch', 'status'], name='map_atm_branch__4b5212_idx'),
        ),
        migrations.AddIndex(
            model_name='atm',
            index=models.Index(fields=['latitude', 'longitude'], name='map_atm_latitud_c70ad5_idx'),
        ),
    ]
